version: '3.8'

services:
  programming-bot:
    build: .
    container_name: programming-bot-2025
    restart: unless-stopped
    ports:
      - "8100:8100"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Berlin
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_MODEL=claude-sonnet-4-20250726
      - FLASK_ENV=production
      - PYTHONPATH=/app
    healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8100/"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 40s
    networks:
      programming-bot-network:
        driver: bridge
